### ISSUE TITLE
How to disable rotation x or  y or z in chart 

### ISSUE THREAD

**Issue by zSakuraEvilz** [jamesleesaunders/d3-x3d#202]
Hi everyone
I found a way to disable all rotations in the chart.
Bằng cách overwrite  x3dom.Viewarea.prototype.onDrag
`
x3dom.Viewarea.prototype.onDrag = function (x, y, buttonState) {
  // ..
  if (buttonState === 1) {
    return;
  }
}
`
However, I want to disable rotation only z.
How to disable rotation x or y or z in the chart?
Pls, help me.
Thank

**Comment by jamesleesaunders** [comment]
HI @zSakuraEvilz apologies for late reply. This is probably a question for the main x3dom project rather than the d3-x3dom project.
I how you figured it out.
