### ISSUE TITLE
X_ITE urls

### ISSUE THREAD

**Issue by create3000** [jamesleesaunders/d3-x3d#207]
X_ITE is now hosted on create3000.github.io, see https://create3000.github.io/x_ite/#github-cdn. The domain http://create3000.de will be shutdown 2022 in May.

New URL's are:

```html
<link rel="stylesheet" type="text/css" href="https://create3000.github.io/code/x_ite/latest/dist/x_ite.css"/>
<script type="text/javascript" src="https://create3000.github.io/code/x_ite/latest/dist/x_ite.min.js"></script>
```

You may want to update the README file.

Besides this X_ITE now supports the Texture3D and VolumeRendering component. Supported 3D texture formats are NRRD, and DICOM.

Best regards,
Holger

**Comment by jamesleesaunders** [comment]
Thanks for the updated URLs. I have now updated the README.
Interesting, you say X_ITE also now supports Volume Rendering 👍  

I have it working on X3DOM here:
https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X3DOM/chart/VolumeSliceChart.html

But could not get it working on X_ITE:
https://raw.githack.com/jamesleesaunders/d3-x3d/master/examples/X_ITE/chart/VolumeSliceChart.html

Getting errors:
```
x_ite.min.js:18 XML Parser Error: Unkown node type 'ENVIRONMENT', you probably have insufficient component/profile statements.
nodeElement @ x_ite.min.js:18
x_ite.min.js:18 XML Parser Error: Unkown node type 'IMAGETEXTUREATLAS', you probably have insufficient component/profile statements.
nodeElement @ x_ite.min.js:18
x_ite.min.js:18 XML Parser Error: Unkown node type 'MPRVOLUMESTYLE', you probably have insufficient component/profile statements.
```

TBH I haven't looked fully into it but are there any obvious fixes I could make to get it working on X_ITE also?

Thanks again for the URL update!

**Comment by create3000** [comment]
These nodes are non standard and not implemented by X_ITE, sorry. Although ImageTextureAtlas was in discussion for X3Dv4 and seems to me very useful. X_ITE implements only standard nodes.

Texturing3D component:
https://www.web3d.org/documents/specifications/19775-1/V3.3/Part01/components/texture3D.html
VolumeRendering component:
https://www.web3d.org/specifications/X3Dv4Draft/ISO-IEC19775-1v4-CD1/Part01/components/volume.html
