### ISSUE TITLE
Contact and credit original authors

### ISSUE THREAD

**Issue by jamesleesaunders** [jamesleesaunders/d3-x3d#8]
Contact the original authors:
* @fabid (Fabian Dubois) - original author of surface area.
* @camio (David Sankel) - original author of bar chart.
Asking their blessing to use their code, credit them and possibly invite them to contribute to d3-x3d.

**Comment by camio** [comment]
> Asking their blessing to use their code

Sure :)

**Comment by jamesleesaunders** [comment]
Thanks David!
Please feel free to contribute join in with d3-x3d if you are still playing in this area.

**Comment by fabid** [comment]
Sure, good to see that you are taking over! That is the kind of project I had in mind, but don't have much time for it at the moment.

**Comment by jamesleesaunders** [comment]
Thanks @fabid!
Totally understand time. 
All the best, Jim
